### ISSUE TITLE
auth/register and login not working

### ISSUE THREAD

**Issue by Pukhraj85** [ed-roh/mern-social-media#16]
![Screenshot from 2023-01-06 20-04-08](https://user-images.githubusercontent.com/120653585/211033108-8c5609c9-7f9c-437c-a325-b55634c5d81e.png)
Hello! When I try to log in I get this error: "POST http://localhost:3001/auth/login 400 (Bad Request) Form.jsx:82". I did not change any of the backend code and I connected to mongodb, I even put your predefined users and posts in collections and tried one of them to log in and it is not working. What should I do?

**Comment by Shubhamnitjsr093** [comment]
@Pukhraj85 how did you resolved this error
