### ISSUE TITLE
http://localhost:/assets/${image} how to get the image file in frontend without storing it

### ISSUE THREAD

**Issue by amareshcoding** [ed-roh/mern-social-media#29]
here we are trying to get the image file in the front end, but we did not store it on getting the user data, how to this issue, same issue after deployment as well

![image](https://user-images.githubusercontent.com/96060638/216431538-b35ba359-bc02-42a3-aa09-aafbe9491cdc.png)

**Comment by Rishabh-Singh-Codes** [comment]
Port is not mentioned in the URL mentioned.

**Comment by amareshcoding** [comment]
Thanks, Rishabh, 
got it in the later part of the video
