### ISSUE TITLE
Form.jsx:61          POST http://localhost:5000/auth/register 404 (Not Found)

### ISSUE THREAD

**Issue by zoraizbinzahid** [ed-roh/mern-social-media#35]
Hey There, 
                  I'm getting this error while posting Register request from this code: 
const savedUserResponse = await fetch(
      "http://localhost:5000/auth/register",
      {
        method: "POST",
        body: formData,
      }
    );

need Help :(

**Comment by rutujp78** [comment]
Check the port number and routes in server directory.

**Comment by zoraizbinzahid** [comment]
>

**Comment by zoraizbinzahid** [comment]
> Check the port number and routes in server directory.

PORT: const PORT = process.env.PORT || 5000;
Route: app.use("auth/register", upload.single("Picture"), register);

cant find out the error :(

**Comment by Shubhamnitjsr093** [comment]
how did you solved this error

**Comment by rutujp78** [comment]
app.use -> app.post 
.use() method is used for middleware and .post() is function to send data to backend.
