### ISSUE TITLE
When I deploy the backend, Signup functionality not work in frontend, when I check this in Postman they work properly, but not work in frontend,Please give me suggestion What I do, then they work

### ISSUE THREAD

**Issue by sejal710** [ed-roh/mern-social-media#41]

**Comment by arshali2774** [comment]
Same here, when I register then the page is stuck, on the register page and there is no response from the server.
i have copied the code still there is no progress

![Screenshot (110)](https://user-images.githubusercontent.com/56296638/224001787-f0413392-f679-4e3e-8b81-b2791f59dca1.png)
