### ISSUE TITLE
fileUrlToPath issue

### ISSUE THREAD

**Issue by ProfCappy** [ed-roh/mern-social-media#8]
when ever i try to run the server i get this error, any help?

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index.js`
file:///C:/Users/Cappy/Desktop/social%20media%20proj/server/index.js:10
import { fileURlToPath } from "url";
         ^^^^^^^^^^^^^
SyntaxError: The requested module 'url' does not provide an export named 'fileURlToPath'

**Comment by chaygosavi** [comment]
It's "URL" not "URI" :)
